// Bless the cute emperor 🍑

Class KirinPlayer : SWWMPlayer
{
	int SpellSel;

	Default
	{
		Tag "$T_KIRIN";
		Height 53;
		Mass 60;
		Player.DisplayName "$T_KIRIN";
		Player.StartItem "KirinPistol";
		Player.StartItem "KirinPistolAmmo", 16;
		Player.StartItem "KirinUnarmed";
		Player.StartItem "KirinMana", 100;
		Player.StartItem "KirinInternalArmor";
		Player.JumpZ 9;
		Player.AttackZOffset 10;
		Player.ViewHeight 49;
		Player.SoundClass "kirin";
		Player.ViewBob .7;
		SWWMPlayer.MoveSpeed .5, 1.2;
		SWWMPlayer.DodgeSpeed 15;
		SWWMPlayer.ResurrectType RT_RESPAWN;
		SWWMPlayer.PainThresholds 0, 5, 20, 50;
		SWWMPlayer.HealthDecrease 50, 10;
		SWWMPlayer.DodgeIFrames 10;
		+SWWMPLAYER.CANDODGE;
		+SWWMPLAYER.CANWALLCLIMB;
	}

	override Weapon PickWeapon( int slot, bool checkammo )
	{
		if ( (slot >= 6) && (slot <= 9) ) EventHandler.SendNetworkEvent("kirinspellslot",slot-6);
		else if ( slot == 0 ) EventHandler.SendNetworkEvent("kirinspellslot",4);
		else return Super.PickWeapon(slot,checkammo);
		return player.ReadyWeapon;
	}
}

